### ISSUE TITLE
Excuse me, could you tell what the 'test_lag.csv' is? 

### ISSUE THREAD

**Issue by cjlala** [anhquan0412/Predict_Future_Sales#2]
I have tried several methods, like merge 'test.csv' with 'new_sales_lag.csv' and do the prediction. But the result is apparently wrong? Could you tell me how to fix it? plz.

**Comment by anhquan0412** [comment]
You can see my comment here
https://github.com/anhquan0412/Predict_Future_Sales/issues/1#issuecomment-418536118
