### ISSUE TITLE
pandas error 

### ISSUE THREAD

**Issue by Lg955** [anhquan0412/Predict_Future_Sales#4]
when run the generate_lag_features.py, the code `gb = sales.groupby(index_cols,as_index=False).agg({'item_cnt_day':{'target':'sum'}})` cause a error, how to slove it?
 (numpy 1.19.5
pandas 1.1.5
scipy 1.4.1
sklearn 0.22.2.post1)

![image](https://user-images.githubusercontent.com/69025725/120884959-d92c3580-c618-11eb-83e7-610aa62b6957.png)

**Comment by entzyeung** [comment]
> when run the generate_lag_features.py, the code `gb = sales.groupby(index_cols,as_index=False).agg({'item_cnt_day':{'target':'sum'}})` cause a error, how to slove it? (numpy 1.19.5 pandas 1.1.5 scipy 1.4.1 sklearn 0.22.2.post1)
> 
> ![image](https://user-images.githubusercontent.com/69025725/120884959-d92c3580-c618-11eb-83e7-610aa62b6957.png)

@Lg955 did you solve it? if yes, would you please tell me how?

**Comment by Lg955** [comment]
try this `.agg({'item_cnt_day': ['sum']})`

**Comment by entzyeung** [comment]
> try this `.agg({'item_cnt_day': ['sum']})`

it works, thank you!
